/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2019-03-21 11:45:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.side;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import user.model.vo.LookBomUser;
import search.model.vo.Search;

public final class side1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/side/../common/footer.jsp", Long.valueOf(1553168705425L));
    _jspx_dependants.put("/views/side/../common/header.jsp", Long.valueOf(1553168574400L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("user.model.vo.LookBomUser");
    _jspx_imports_classes.add("search.model.vo.Search");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"../../resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\tbody{margin:0; padding:0;}\r\n");
      out.write("\t.stop{\r\n");
      out.write("\tposition:absolute;\r\n");
      out.write("\ttop:50vh;\r\n");
      out.write("\t}\r\n");
      out.write("\t.sidebar{\r\n");
      out.write("\t/* border:1px solid black; */\r\n");
      out.write("\twidth:11vw;\r\n");
      out.write("\theight:35vh;\r\n");
      out.write("\tpadding:1vw;\r\n");
      out.write("\tposition:sticky;\r\n");
      out.write("\tleft:1vw;\r\n");
      out.write("\ttop: 25vh;\r\n");
      out.write("\tbackground:white;\r\n");
      out.write("\tbox-shadow:0 10px 20px 0 rgba(0,0,0,0.2);\r\n");
      out.write("\tz-index:100;\r\n");
      out.write("\t}\r\n");
      out.write(".slides {\r\n");
      out.write("   z-index:2;\r\n");
      out.write("    width: 80vw;\r\n");
      out.write("    height: 80vh;\r\n");
      out.write("    display: block;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("     padding: 0;\r\n");
      out.write("    position: relative;\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slides * {\r\n");
      out.write("\tz-index:0;\r\n");
      out.write("    user-select: none;\r\n");
      out.write("    -ms-user-select: none;\r\n");
      out.write("    -moz-user-select: none;\r\n");
      out.write("    -khtml-user-select: none;\r\n");
      out.write("    -webkit-user-select: none;\r\n");
      out.write("    -webkit-touch-callout: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slides input { display: none; }\r\n");
      out.write("\r\n");
      out.write(".slide-container { display: block; }\r\n");
      out.write("\r\n");
      out.write(".slide {\r\n");
      out.write("    top: 0;\r\n");
      out.write("    opacity: 0;\r\n");
      out.write("    width: 80vw;\r\n");
      out.write("    height: 80vh;\r\n");
      out.write("    display: block;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("\r\n");
      out.write("    transform: scale(0);\r\n");
      out.write("\r\n");
      out.write("    transition: all .7s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slide img {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav label {\r\n");
      out.write("    width: 200px;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    display: none;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("\r\n");
      out.write("      opacity: 0;\r\n");
      out.write("    z-index: 9;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("\r\n");
      out.write("    transition: opacity .2s;\r\n");
      out.write("\r\n");
      out.write("    color: #FFF;\r\n");
      out.write("    font-size: 156pt;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    line-height: 380px;\r\n");
      out.write("    font-family: \"Varela Round\", sans-serif;\r\n");
      out.write("    background-color: rgba(255, 255, 255, .3);\r\n");
      out.write("    text-shadow: 0px 0px 15px rgb(119, 119, 119);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slide:hover + .nav label { opacity: 0.5; }\r\n");
      out.write("\r\n");
      out.write(".nav label:hover { opacity: 1; }\r\n");
      out.write("\r\n");
      out.write(".nav .next { right: 0; }\r\n");
      out.write("\r\n");
      out.write("input:checked + .slide-container  .slide {\r\n");
      out.write("    opacity: 1;\r\n");
      out.write("\r\n");
      out.write("    transform: scale(1);\r\n");
      out.write("\r\n");
      out.write("    transition: opacity 1s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input:checked + .slide-container .nav label { display: block; }\r\n");
      out.write("\r\n");
      out.write(".nav-dots {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    bottom: 9px;\r\n");
      out.write("    height: 11px;\r\n");
      out.write("    display: block;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-dots .nav-dot {\r\n");
      out.write("    top: -5px;\r\n");
      out.write("    width: 11px;\r\n");
      out.write("    height: 11px;\r\n");
      out.write("    margin: 0 4px;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    border-radius: 100%;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    background-color: rgba(0, 0, 0, 0.6);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-dots .nav-dot:hover {\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    background-color: rgba(0, 0, 0, 0.8);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input#img-1:checked ~ .nav-dots label#img-dot-1,\r\n");
      out.write("input#img-2:checked ~ .nav-dots label#img-dot-2,\r\n");
      out.write("input#img-3:checked ~ .nav-dots label#img-dot-3,\r\n");
      out.write("input#img-4:checked ~ .nav-dots label#img-dot-4,\r\n");
      out.write("input#img-5:checked ~ .nav-dots label#img-dot-5,\r\n");
      out.write("input#img-6:checked ~ .nav-dots label#img-dot-6 {\r\n");
      out.write("    background: rgba(0, 0, 0, 0.8);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("    ");

    LookBomUser loginUser = (LookBomUser)session.getAttribute("loginUser");
/*     Search search = (Search)session.getAttribute("search"); */
    
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<script src=\"../../resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction show(){\r\n");
      out.write("\t\t\tvar max = document.getElementById(\"searchmax\");\r\n");
      out.write("\t\t\tmax.style.display = \"inline-block\";\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\twindow.onload = function() {\r\n");
      out.write("\t\t\tdocument.getElementById('close').onclick = function() { \r\n");
      out.write("\t\t\t\tvar max = document.getElementById(\"searchmax\");\r\n");
      out.write("\t\t\t\tmax.style.display = \"none\"; } \r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t/*  $(window).scroll(function(){\r\n");
      out.write("\t\tvar scroll = $(window).scrollTop();\r\n");
      out.write("\t\tif(scroll != 0){\r\n");
      out.write("\t\t$(\".header\").addClass(\".change1\");\r\n");
      out.write("\t\t$(\".hdheight\").addClass(\".change\");\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t$(\".header\").removeClass(\".change1\");\r\n");
      out.write("\t\t$(\".hdheight\").removeClass(\".change\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});  */\r\n");
      out.write("\t $(window).scroll(function(){\r\n");
      out.write("\t\t\tvar scroll = $(window).scrollTop();\r\n");
      out.write("\t\t\tconsole.log(scroll);\r\n");
      out.write("\t\t\tif(scroll > 0){\r\n");
      out.write("\t\t\t$(\".header\").addClass(\"change1\");\r\n");
      out.write("\t\t\t$(\".hdheight\").addClass(\"change\");\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t$(\".header\").removeClass(\"change1\");\r\n");
      out.write("\t\t\t$(\".hdheight\").removeClass(\"change\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tconsole.log(scroll);\r\n");
      out.write("\t\t}); \r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t.change1{\r\n");
      out.write("\ttop:-50px;\r\n");
      out.write("\t\r\n");
      out.write("\t/* backgound: rgba(255,255,255,0.5); */\r\n");
      out.write("\t\t}\r\n");
      out.write("\t.change{\r\n");
      out.write("\t/*  backgound: rgba(255,255,255,0.5);  */\r\n");
      out.write("\t border-bottom: 1px solid rgba(0,0,0,0.5);\r\n");
      out.write("\t opacity:0.7;\r\n");
      out.write("\t}\r\n");
      out.write("\t.header {\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\tposition:fixed;\r\n");
      out.write("\tz-index:10;\r\n");
      out.write("\theight:150px;\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t.hdheight{\r\n");
      out.write("\tbackground: white;\r\n");
      out.write("\theight:170px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.topbar {\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\theight:50px;\r\n");
      out.write("\tbackground:black;\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\tpadding:  0px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.logo2{\r\n");
      out.write("\twidth:100px;\r\n");
      out.write("\theight:100px;\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\tpadding : 10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.logo{\r\n");
      out.write("\twidth:200px;\r\n");
      out.write("\theight:50px;\r\n");
      out.write("\tposition:relative;\r\n");
      out.write("\ttop:10px;\r\n");
      out.write("\tleft:10px;\r\n");
      out.write("\tpadding-botton: 20px;\r\n");
      out.write("\t}\r\n");
      out.write("\tbody{\r\n");
      out.write(" color:black;\r\n");
      out.write(" font-family:\"맑은고딕\";\r\n");
      out.write(" font-size: 15px;\r\n");
      out.write(" font-weight: bold;\r\n");
      out.write("\r\n");
      out.write(" }\r\n");
      out.write("\t a{\r\n");
      out.write(" text-decoration:none;\r\n");
      out.write(" }\r\n");
      out.write(" \tul,ol,li{\r\n");
      out.write(" margin:0;\r\n");
      out.write(" padding:0;\r\n");
      out.write(" list-style-type:none;\r\n");
      out.write(" }\r\n");
      out.write(" \t#navi li{\r\n");
      out.write(" float:left;\r\n");
      out.write(" position:relative;\r\n");
      out.write(" top:10px;\r\n");
      out.write(" line-height:40px;\r\n");
      out.write(" color:black;\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write(" \t#navi li a{\r\n");
      out.write("  display:block;\r\n");
      out.write("  padding:0 10px;\r\n");
      out.write("  color:black;\r\n");
      out.write("  margin:0;'\r\n");
      out.write("  \r\n");
      out.write(" \r\n");
      out.write(" }\r\n");
      out.write(" \t#navi > li >a:hover{\r\n");
      out.write(" font-weight:900;\r\n");
      out.write(" border-bottom:3px solid black;\r\n");
      out.write(" background: white;\r\n");
      out.write(" color:yellow\r\n");
      out.write(" }\r\n");
      out.write(" #navi > li >a:visited{\r\n");
      out.write("  border-bottom:3px solid black;\r\n");
      out.write(" }\r\n");
      out.write(" \t#navi li ul{\r\n");
      out.write(" position:absolute;\r\n");
      out.write(" opacity:0;\r\n");
      out.write(" width:180px;\r\n");
      out.write(" box-shadow:0 10px 20px 0 rgba(0,0,0,0.2);\r\n");
      out.write(" -webkit-boix-shadow:0 12px 25px 0 rgba(0,0,0,0.2);\r\n");
      out.write(" }\r\n");
      out.write(" \t#navi li:hover ul{\r\n");
      out.write(" opacity:1;\r\n");
      out.write(" }\r\n");
      out.write(" \t#navi li ul li{\r\n");
      out.write(" float:none;\r\n");
      out.write(" position:static;\r\n");
      out.write(" height:0;\r\n");
      out.write(" line-height:0;\r\n");
      out.write(" background:none;\r\n");
      out.write(" }\r\n");
      out.write(" \t#navi li:hover ul li{\r\n");
      out.write(" padding:10px 10;\r\n");
      out.write(" height:50px;\r\n");
      out.write(" line-height:40px;\r\n");
      out.write(" /* background:rgba(0,0,0,0.4); */\r\n");
      out.write(" background:white;\r\n");
      out.write(" }\r\n");
      out.write(" \t#navi li ul li a:hover{\r\n");
      out.write(" \tfont-weight:900;\r\n");
      out.write(" \t}\r\n");
      out.write("\t #mybar{\r\n");
      out.write(" float:left;\r\n");
      out.write(" color:black;\r\n");
      out.write(" font-size:small;\r\n");
      out.write(" }\r\n");
      out.write("\t #mybar img{\r\n");
      out.write(" width:15px;\r\n");
      out.write(" height:15px;\r\n");
      out.write(" padding-top:15px;\r\n");
      out.write(" padding-left:15px;\r\n");
      out.write(" }\r\n");
      out.write("\t.myBtn img{\r\n");
      out.write("\t\twidth:50px;\r\n");
      out.write(" \theight:50px;\r\n");
      out.write("\r\n");
      out.write(" }\r\n");
      out.write(" \t.myBtn{\r\n");
      out.write(" /* \twidth:50px;\r\n");
      out.write(" \theight:50px;\r\n");
      out.write(" \tdisplay:inline;;\r\n");
      out.write(" \tposition:relative;\r\n");
      out.write(" \ttop:30px;\r\n");
      out.write(" \t */\r\n");
      out.write(" \tbackground-color: white; /* Green */\r\n");
      out.write(" \tborder: none;\r\n");
      out.write("  /*   position:relative;\r\n");
      out.write(" \ttop:30px;\r\n");
      out.write(" \tleft:-20px; */\r\n");
      out.write("  \twidth:50px;\r\n");
      out.write(" \theight:50px;\r\n");
      out.write("\t\r\n");
      out.write("\t  display: inline-block;\r\n");
      out.write("\r\n");
      out.write(" \t}\r\n");
      out.write(" \t.myBtn:hover{\r\n");
      out.write(" \tcursor:pointer;\r\n");
      out.write(" \t}\r\n");
      out.write("\r\n");
      out.write("        /* The Close Button */\r\n");
      out.write("       #close {\r\n");
      out.write("            color: white;\r\n");
      out.write("            float: right;\r\n");
      out.write("            font-size: 100px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            position:relative;\r\n");
      out.write("            top:150px;\r\n");
      out.write("            left:-50px;\r\n");
      out.write("        }\r\n");
      out.write("       #close:hover,\r\n");
      out.write("        #close:focus {\r\n");
      out.write("            color: black;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        #loginUser h3{\r\n");
      out.write("        padding:0px;\r\n");
      out.write("        margin:0px;\r\n");
      out.write("        color: white;\r\n");
      out.write("        float : left;\r\n");
      out.write("        position:relative;\r\n");
      out.write("        top:10px;\r\n");
      out.write("        left:10px;\r\n");
      out.write("        }\r\n");
      out.write("    \r\n");
      out.write("\t#rank {\r\n");
      out.write("/* \tposition:relative;\r\n");
      out.write("\ttop:30px;\r\n");
      out.write("\tleft:100px; */\r\n");
      out.write("\twidth:200px;\r\n");
      out.write("\theight:35px;\r\n");
      out.write("/* \tfloat:left; */\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#searchmax{\r\n");
      out.write("\tdisplay: none;  /* Hidden by default */\r\n");
      out.write("            position: fixed; /* Stay in place */\r\n");
      out.write("            z-index: 1; /* Sit on top */\r\n");
      out.write("            left: 0;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            width: 100vw; /* Full width */\r\n");
      out.write("            height: 100vh; /* Full height */\r\n");
      out.write("            overflow: auto; /* Enable scroll if needed */\r\n");
      out.write("            background-color: rgb(0,0,0); /* Falsemiack color */\r\n");
      out.write("            background-color: rgba(0,0,0,0.4); /* Black w/ opacity */\r\n");
      out.write("           \r\n");
      out.write("\t}\r\n");
      out.write("\t#blackwindow{\r\n");
      out.write("\tdisplay:inline-block;\r\n");
      out.write("\twidth:366px; height:34px;\r\n");
      out.write("\tborder:3px solid black;\r\n");
      out.write("\tbackground:white;\r\n");
      out.write("\t\r\n");
      out.write("\tposition:relative;\r\n");
      out.write("\ttop:100px;\r\n");
      out.write("\tleft: 900px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t#searchingbar  {\r\n");
      out.write("\twidth: 348px; height: 21px;\r\n");
      out.write("\tmargin: 6px 0 0 9px;\r\n");
      out.write("\tfont-weight:bold;\r\n");
      out.write("\tborder:0;\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\tline-height:25px;\r\n");
      out.write("\toutline:none;\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\t#sch_smit{\r\n");
      out.write("\twidth: 54px; height:40px;\r\n");
      out.write("\tbackground:black;\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\tmargin:0; border:0;\r\n");
      out.write("\tfont-weight:bold;\r\n");
      out.write("\tborder-radius: 1px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tvertical-align: top;\r\n");
      out.write("\tposition:relative;\r\n");
      out.write("\tleft:370px;\r\n");
      out.write("\ttop:-32px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#topsearch{\r\n");
      out.write("\tposition:relative;\r\n");
      out.write("\tleft:800px;\r\n");
      out.write("\ttop:200px;\r\n");
      out.write("\twidth:200px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body style=\"margin:0px; padding:0px; width:100%; height:100%;\">\r\n");
      out.write("<header class=\"header\">\r\n");
      out.write("<div class=\"hdheight\">\r\n");
      out.write("<div class=\"topbar\">\r\n");
      out.write("\t<div class=\"topbar\" id=\"loginUser\" style=\"background: pink; height: 50px;; width: 300px;\"><!-- 로그인시 유저명이랑 포인트  -->\r\n");
      out.write(" \t \t");
if(loginUser != null) {
      out.write("\r\n");
      out.write("\t\t<h3>이름 : ");
      out.print(loginUser.getUserName() );
      out.write("</h3>&nbsp;&nbsp;\t<h3>포인트 : ");
      out.print( loginUser.getPoint() );
      out.write("</h3>\r\n");
      out.write("\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t<h3>이름      &nbsp;&nbsp;</h3><h3>포인트</h3>\r\n");
      out.write("\t\t");
} 
      out.write(" \r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class =\"top_fix_zone\" id=\"topbar1\">\r\n");
      out.write("<a href=\"#\" ><img src=\"/semi/resources/images/로고2.png\" id=\"logo2\" class=\"logo2\"></a>\r\n");
      out.write("<a href=\"#\"><img src=\"/semi/resources/images/로고.png\" id=\"logo\" class=\"logo\"></a>\r\n");
      out.write("\r\n");
      out.write("<div  style=\"width:25%;height:130px;  float:right;\">\r\n");
      out.write("<td><a id=\"mybar\" href=\"/semi/views/user/login.jsp\"><img src=\"/semi/resources/images/로그인.jpg\">로그인</a></td>\r\n");
      out.write("<td><a id=\"mybar\" href=\"#\"><img src=\"/semi/resources/images/회원가입.jpg\">회원가입</a></td>\r\n");
      out.write("<td><a id=\"mybar\" href=\"#\"><img src=\"/semi/resources/images/장바구니.jpg\">장바구니</a></td>\r\n");
      out.write("<td><a id=\"mybar\" href=\"#\"><img src=\"/semi/resources/images/마이페이지.jpg\">마이페이지</a></td>\r\n");
      out.write("\r\n");
      out.write("<!-- 실시간 랭킹바  -->\r\n");
      out.write("<table>\r\n");
      out.write("<tr>\r\n");
      out.write("<th>\r\n");
      out.write("<select id=\"rank\" name=\"rank\">\r\n");
      out.write("\t<option id=\"rank1\">1. </option>\r\n");
      out.write("\t<option id=\"rank2\">2. </option>\r\n");
      out.write("\t<option id=\"rank3\">3. </option>\r\n");
      out.write("\t<option id=\"rank4\">4. </option>\r\n");
      out.write("\t<option id=\"rank5\">5. </option>\r\n");
      out.write("\t<option id=\"rank6\">6. </option>\r\n");
      out.write("\t<option id=\"rank7\">7. </option>\r\n");
      out.write("\t<option id=\"rank8\">8. </option>\r\n");
      out.write("\t<option id=\"rank9\">9. </option>\r\n");
      out.write("\t<option id=\"rank10\">10. </option>\r\n");
      out.write("</select>\r\n");
      out.write("</th>\r\n");
      out.write("<th><button class=\"myBtn\"  onclick=\"show();\"><img src=\"/semi/resources/images/검색.jpg\"></button></th>\r\n");
      out.write("<tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!--  메뉴 바 -->\r\n");
      out.write("<ul id=\"navi\">\t\r\n");
      out.write("<li class=\"on\"><a class=\"menu1\" href=\"/semi/views/side/side1.jsp\">MEN</a>\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t\t<li><a href=\"#\">1</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\">2</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\">3</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\">4</a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("</li>\r\n");
      out.write("<li><a class=\"menu2\" href=\"/semi/views/side/side2.jsp\">WOMEN</a>\r\n");
      out.write("<ul>\r\n");
      out.write("\t\t<li><a href=\"#\">1</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\">2</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\">3</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\">4</a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("</li>\r\n");
      out.write("<li><a class=\"menu3\" href=\"/semi/views/side/side3.jsp\">BRAND</a>\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t\t<li><a href=\"#\">1</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\">2</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\">3</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\">4</a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("</li>\r\n");
      out.write("<li><a class=\"menu4\" href=\"/semi/views/side/side4.jsp\">ACC</a>\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t\t<li><a href=\"#\">1</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\">2</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\">3</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\">4</a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("</li>\r\n");
      out.write("<li><a class=\"menu5\" href=\"/semi/views/side/side5.jsp\">BRAND</a>\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t\t<li><a href=\"#\">1</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\">2</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\">3</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\">4</a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("</li>\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"searchmax\">\r\n");
      out.write("\t<span id=\"blackwindow\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"search\"   id=\"searchingbar\">&nbsp;\r\n");
      out.write("\t\t\t\t<button type=\"submit\" id=\"sch_smit\">검색</button>\r\n");
      out.write("\t</span>\r\n");
      out.write("\t<div id=\"topsearch\">\r\n");
      out.write("\t<h1 style=\"border-bottom:2px solid black\">인기   검색어</h1>\r\n");
      out.write("\t<table>\r\n");
      out.write("\t<tr><td>1위 &nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\r\n");
      out.write("\t<tr><td></td></tr>\r\n");
      out.write("\t<tr><td>2위 &nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\r\n");
      out.write("\t<tr><td></td></tr>\r\n");
      out.write("\t<tr><td>3위 &nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\r\n");
      out.write("\t<tr><td></td></tr>\r\n");
      out.write("\t<tr><td>4위 &nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\r\n");
      out.write("\t<tr><td></td></tr>\r\n");
      out.write("\t<tr><td>5위 &nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\r\n");
      out.write("\t<tr><td></td></tr>\r\n");
      out.write("\t<tr><td>6위 &nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\r\n");
      out.write("\t<tr><td></td></tr>\r\n");
      out.write("\t<tr><td>7위 &nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\r\n");
      out.write("\t<tr><td></td></tr>\r\n");
      out.write("\t<tr><td>8위 &nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\r\n");
      out.write("\t<tr><td></td></tr>\r\n");
      out.write("\t<tr><td>9위 &nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\r\n");
      out.write("\t<tr><td></td></tr>\r\n");
      out.write("\t<tr><td>10위 &nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\r\n");
      out.write("\t\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<span id=\"close\" >&times;</span> \r\n");
      out.write("</div>\r\n");
      out.write("<!-- 검색창  -->\r\n");
      out.write("</div>\r\n");
      out.write("</header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<aside class=\"sidebar\">\r\n");
      out.write("<table>\r\n");
      out.write("\t<tr><td style=\"padding:1vh\"><a href=\"#\">NEW</a></td></tr>\r\n");
      out.write("\t<tr><td style=\"padding:1vh\"><a href=\"#\">BEST</a></td></tr>\r\n");
      out.write("\t<tr><td style=\"padding:1vh\"><a href=\"#\">Outer</a></td></tr>\r\n");
      out.write("\t<tr><td style=\"padding:1vh\"><a href=\"#\">Top</a></td></tr>\r\n");
      out.write("\t<tr><td style=\"padding:1vh\"><a href=\"#\">Bottom</a></td></tr>\r\n");
      out.write("\t<tr><td style=\"padding:1vh\"><a href=\"#\">Accessories</a></td></tr>\r\n");
      out.write("\t<tr><td style=\"padding:1vh\"><a href=\"#\">Shoes</a></td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</aside>\r\n");
      out.write("\r\n");
      out.write("<ul class=\"slides\">\r\n");
      out.write("    <input type=\"radio\" name=\"radio-btn\" id=\"img-1\" checked />\r\n");
      out.write("    <li class=\"slide-container\">\r\n");
      out.write("        <div class=\"slide\">\r\n");
      out.write("            <a href=\"#\"><img name=\"img1\" src=\"http://farm9.staticflickr.com/8072/8346734966_f9cd7d0941_z.jpg\" /></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"nav\">\r\n");
      out.write("            <label for=\"img-6\" class=\"prev\">&#x2039;</label>\r\n");
      out.write("            <label for=\"img-2\" class=\"next\">&#x203a;</label>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("\r\n");
      out.write("    <input type=\"radio\" name=\"radio-btn\" id=\"img-2\" />\r\n");
      out.write("    <li class=\"slide-container\">\r\n");
      out.write("        <div class=\"slide\">\r\n");
      out.write("          <a href=\"#\"><img name=\"img2\" src=\"http://farm9.staticflickr.com/8504/8365873811_d32571df3d_z.jpg\" /></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"nav\">\r\n");
      out.write("            <label for=\"img-1\" class=\"prev\">&#x2039;</label>\r\n");
      out.write("            <label for=\"img-3\" class=\"next\">&#x203a;</label>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("\r\n");
      out.write("    <input type=\"radio\" name=\"radio-btn\" id=\"img-3\" />\r\n");
      out.write("    <li class=\"slide-container\">\r\n");
      out.write("        <div class=\"slide\">\r\n");
      out.write("          <a href=\"#\"><img name= \"img3\"src=\"http://farm9.staticflickr.com/8068/8250438572_d1a5917072_z.jpg\" /></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"nav\">\r\n");
      out.write("            <label for=\"img-2\" class=\"prev\">&#x2039;</label>\r\n");
      out.write("            <label for=\"img-4\" class=\"next\">&#x203a;</label>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("\r\n");
      out.write("    <input type=\"radio\" name=\"radio-btn\" id=\"img-4\" />\r\n");
      out.write("    <li class=\"slide-container\">\r\n");
      out.write("        <div class=\"slide\">\r\n");
      out.write("         <a href=\"#\"><img src=\"http://farm9.staticflickr.com/8061/8237246833_54d8fa37f0_z.jpg\" /></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"nav\">\r\n");
      out.write("            <label for=\"img-3\" class=\"prev\">&#x2039;</label>\r\n");
      out.write("            <label for=\"img-5\" class=\"next\">&#x203a;</label>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("\r\n");
      out.write("    <input type=\"radio\" name=\"radio-btn\" id=\"img-5\" />\r\n");
      out.write("    <li class=\"slide-container\">\r\n");
      out.write("        <div class=\"slide\">\r\n");
      out.write("          <a href=\"#\"><img src=\"http://farm9.staticflickr.com/8055/8098750623_66292a35c0_z.jpg\" /></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"nav\">\r\n");
      out.write("            <label for=\"img-4\" class=\"prev\">&#x2039;</label>\r\n");
      out.write("            <label for=\"img-6\" class=\"next\">&#x203a;</label>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("\r\n");
      out.write("    <input type=\"radio\" name=\"radio-btn\" id=\"img-6\" />\r\n");
      out.write("    <li class=\"slide-container\">\r\n");
      out.write("        <div class=\"slide\">\r\n");
      out.write("         <a href=\"#\"> <img src=\"http://farm9.staticflickr.com/8195/8098750703_797e102da2_z.jpg\" /></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"nav\">\r\n");
      out.write("            <label for=\"img-5\" class=\"prev\">&#x2039;</label>\r\n");
      out.write("            <label for=\"img-1\" class=\"next\">&#x203a;</label>\r\n");
      out.write("        </div>\r\n");
      out.write("    </li>\r\n");
      out.write("\r\n");
      out.write("    <li class=\"nav-dots\">\r\n");
      out.write("      <label for=\"img-1\" class=\"nav-dot\" id=\"img-dot-1\"></label>\r\n");
      out.write("      <label for=\"img-2\" class=\"nav-dot\" id=\"img-dot-2\"></label>\r\n");
      out.write("      <label for=\"img-3\" class=\"nav-dot\" id=\"img-dot-3\"></label>\r\n");
      out.write("      <label for=\"img-4\" class=\"nav-dot\" id=\"img-dot-4\"></label>\r\n");
      out.write("      <label for=\"img-5\" class=\"nav-dot\" id=\"img-dot-5\"></label>\r\n");
      out.write("      <label for=\"img-6\" class=\"nav-dot\" id=\"img-dot-6\"></label>\r\n");
      out.write("    </li>\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".address {\r\n");
      out.write(" font-size:small;\r\n");
      out.write(" }\r\n");
      out.write(" #footer{\r\n");
      out.write(" position:static;\r\n");
      out.write(" bottom:0;\r\n");
      out.write(" width:98vw;\r\n");
      out.write(" align:center;\r\n");
      out.write(" \r\n");
      out.write(" }\r\n");
      out.write(" #footer p{\r\n");
      out.write(" color:rgba(0,0,0,0.5);\r\n");
      out.write(" }\r\n");
      out.write(" #footer a {\r\n");
      out.write(" color:black;\r\n");
      out.write(" }\r\n");
      out.write(" #footer div {\r\n");
      out.write(" margin:20px;\r\n");
      out.write(" padding:20px;\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write("</style>\r\n");
      out.write("<body style=\"margin:0px; padding:0px;\">\r\n");
      out.write("<footer id=\"footer\" >\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("<hr>\r\n");
      out.write("<img src=\"/semi/resources/images/로고2.png\" style=\"width:40px;height:40px;float:left;\"><h1>1644-1234</h1>\r\n");
      out.write("<p style=\"font-size:small\">AM 10:00 ~ PM 05:00<BR>\r\n");
      out.write("Off-Time PM 12:00 ~ PM 2:00<BR>\r\n");
      out.write("DAY OFF (SATURDAY,SUNDAY,HOLIDAY)\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("<a href=\"#\">개인정보취급방침 | 이용약관</a>\r\n");
      out.write("<p class=\"address\">주식회사 그랩(GRAB Co.,Ltd) | 서울특별시 강남구 신사동 640-2 로빈명품관 지하1층 | 사업자등록번호 : 211-88-79575 |<br>\r\n");
      out.write("통신판매업 : 2012-서울강남-01897 | 대표 : 조만호 | 개인정보관리책임자 : 심준섭(<a href=\"mailto:help@musinsa.com\">help@musinsa.com</a>) ｜ 호스팅사업자 : ㈜이호스트ICT</p>\r\n");
      out.write("</div>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
