/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2019-03-20 11:17:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.adminMain;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mainPostUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/adminMain/../common/adminHeader.jsp", Long.valueOf(1553079671118L));
    _jspx_dependants.put("/views/adminMain/../common/footer.jsp", Long.valueOf(1552893242880L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<script src=\"/first/resources/js/jquery-3.3.1.min.js\">\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t#topbar {\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\theight:50px;\r\n");
      out.write("\tbackground:black;\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\tpadding:  0px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#logo2{\r\n");
      out.write("\twidth:100px;\r\n");
      out.write("\theight:100px;\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\tpadding : 10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#logo{\r\n");
      out.write("\twidth:200px;\r\n");
      out.write("\theight:50px;\r\n");
      out.write("\tposition:relative;\r\n");
      out.write("\ttop:10px;\r\n");
      out.write("\tleft:10px;\r\n");
      out.write("\tpadding-botton: 20px;\r\n");
      out.write("\t}\r\n");
      out.write("\tbody{\r\n");
      out.write(" color:black;\r\n");
      out.write(" font-family:\"맑은고딕\";\r\n");
      out.write(" font-size: 15px;\r\n");
      out.write(" font-weight: bold;\r\n");
      out.write("\r\n");
      out.write(" }\r\n");
      out.write("\t a{\r\n");
      out.write(" text-decoration:none;\r\n");
      out.write(" }\r\n");
      out.write(" \tul,ol,li{\r\n");
      out.write(" margin:0;\r\n");
      out.write(" padding:0;\r\n");
      out.write(" list-style-type:none;\r\n");
      out.write(" }\r\n");
      out.write(" \t#navi li{\r\n");
      out.write(" float:left;\r\n");
      out.write(" position:relative;\r\n");
      out.write(" top:10px;\r\n");
      out.write(" line-height:40px;\r\n");
      out.write(" color:black;\r\n");
      out.write(" }\r\n");
      out.write(" \t#navi li a{\r\n");
      out.write("  display:block;\r\n");
      out.write("  padding:0 10px;\r\n");
      out.write("  color:black;\r\n");
      out.write("  margin:0;'\r\n");
      out.write("  \r\n");
      out.write(" \r\n");
      out.write(" }\r\n");
      out.write(" \t#navi li a:hover{\r\n");
      out.write(" font-weight:bold;\r\n");
      out.write(" border-bottom:3px solid black;\r\n");
      out.write(" background: white;\r\n");
      out.write(" color:black;\r\n");
      out.write(" }\r\n");
      out.write(" \t#navi li ul{\r\n");
      out.write(" position:absolute;\r\n");
      out.write(" opacity:0;\r\n");
      out.write(" width:180px;\r\n");
      out.write(" box-shadow:0 10px 20px 0 rgba(0,0,0,0.2);\r\n");
      out.write(" -webkit-boix-shadow:0 12px 25px 0 rgba(0,0,0,0.2);\r\n");
      out.write(" }\r\n");
      out.write(" \t#navi li:hover ul{\r\n");
      out.write(" opacity:1;\r\n");
      out.write(" }\r\n");
      out.write(" \t#navi li ul li{\r\n");
      out.write(" float:none;\r\n");
      out.write(" position:static;\r\n");
      out.write(" height:0;\r\n");
      out.write(" line-height:0;\r\n");
      out.write(" background:none;\r\n");
      out.write(" }\r\n");
      out.write(" \t#navi li:hover ul li{\r\n");
      out.write(" padding:10px 10;\r\n");
      out.write(" height:50px;\r\n");
      out.write(" line-height:40px;\r\n");
      out.write(" background:rgba(0,0,0,0.4);\r\n");
      out.write(" \r\n");
      out.write(" }\r\n");
      out.write("\t #mybar{\r\n");
      out.write(" float:left;\r\n");
      out.write(" color:black;\r\n");
      out.write(" font-size:small;\r\n");
      out.write(" }\r\n");
      out.write("\t #mybar img{\r\n");
      out.write(" width:15px;\r\n");
      out.write(" height:15px;\r\n");
      out.write(" padding-top:15px;\r\n");
      out.write(" padding-left:15px;\r\n");
      out.write(" }\r\n");
      out.write("\t#myBtn img{\r\n");
      out.write("\t\twidth:50px;\r\n");
      out.write(" \theight:50px;\r\n");
      out.write("\r\n");
      out.write(" }\r\n");
      out.write(" \t#myBtn{\r\n");
      out.write(" /* \twidth:50px;\r\n");
      out.write(" \theight:50px;\r\n");
      out.write(" \tdisplay:inline;;\r\n");
      out.write(" \tposition:relative;\r\n");
      out.write(" \ttop:30px;\r\n");
      out.write(" \t */\r\n");
      out.write(" \t   background-color: white; /* Green */\r\n");
      out.write(" \t border: none;\r\n");
      out.write("  position:relative;\r\n");
      out.write(" \ttop:30px;\r\n");
      out.write(" \tleft:-20px;\r\n");
      out.write("  \twidth:50px;\r\n");
      out.write(" \theight:50px;\r\n");
      out.write("\t\r\n");
      out.write("\t  display: inline-block;\r\n");
      out.write("\r\n");
      out.write(" \t}\r\n");
      out.write(" \t\t#mybtn:hover{\r\n");
      out.write(" \tcursor:pointer;\r\n");
      out.write(" \t}\r\n");
      out.write("\t/* The Modal (background) */\r\n");
      out.write("        .modal {\r\n");
      out.write("            display: none; /* Hidden by default */\r\n");
      out.write("            position: fixed; /* Stay in place */\r\n");
      out.write("            z-index: 1; /* Sit on top */\r\n");
      out.write("            left: 0;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            width: 100%; /* Full width */\r\n");
      out.write("            height: 100%; /* Full height */\r\n");
      out.write("            overflow: auto; /* Enable scroll if needed */\r\n");
      out.write("            background-color: rgb(0,0,0); /* Fallback color */\r\n");
      out.write("            background-color: rgba(0,0,0,0.4); /* Black w/ opacity */\r\n");
      out.write("        }\r\n");
      out.write("    \r\n");
      out.write("        /* Modal Content/Box */\r\n");
      out.write("        .modal-content {\r\n");
      out.write("            background-color: #fefefe;\r\n");
      out.write("            margin: 15% auto; /* 15% from the top and centered */\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            border: 1px solid #888;\r\n");
      out.write("            width: 50%; /* Could be more or less, depending on screen size */                          \r\n");
      out.write("        }\r\n");
      out.write("        /* The Close Button */\r\n");
      out.write("       .close {\r\n");
      out.write("            color: #aaa;\r\n");
      out.write("            float: right;\r\n");
      out.write("            font-size: 28px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("        .close:hover,\r\n");
      out.write("        .close:focus {\r\n");
      out.write("            color: black;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        #loginUser h3{\r\n");
      out.write("        padding:0px;\r\n");
      out.write("        margin:0px;\r\n");
      out.write("        color: white;\r\n");
      out.write("        float : left;\r\n");
      out.write("        position:relative;\r\n");
      out.write("        top:10px;\r\n");
      out.write("        left:10px;\r\n");
      out.write("        }\r\n");
      out.write("    \r\n");
      out.write("\t#rank {\r\n");
      out.write("\tposition:relative;\r\n");
      out.write("\ttop:30px;\r\n");
      out.write("\tleft:100px;\r\n");
      out.write("\twidth:200px;\r\n");
      out.write("\theight:35px;\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body style=\"margin:0px; padding:0px;\">\r\n");
      out.write("<header>\r\n");
      out.write("<div id=\"topbar\">\r\n");
      out.write("\t<div id=\"loginUser\" style=\"background: pink; height: 50px;; width: 300px;\"><!-- 로그인시 유저명이랑 포인트  -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class =\"top_fix_zone\" id=\"topbar1\">\r\n");
      out.write("<a href=\"#\" ><img src=\"/semi/resources/images/로고2.png\" id=\"logo2\"></a>\r\n");
      out.write("<a href=\"#\"><img src=\"/semi/resources/images/로고.png\" id=\"logo\"></a>\r\n");
      out.write("\r\n");
      out.write("<div  style=\"width:26%;height:130px;  float:right;\">\r\n");
      out.write("<a id=\"mybar\" href=\"#\"><img src=\"/semi/resources/images/로그인.jpg\">상품관리</a>\r\n");
      out.write("<a id=\"mybar\" href=\"#\"><img src=\"/semi/resources/images/회원가입.jpg\">회원관리</a>\r\n");
      out.write("<a id=\"mybar\" href=\"#\"><img src=\"/semi/resources/images/게시판관리.jpg\">게시판관리</a>\r\n");
      out.write("<a id=\"mybar\" href=\"#\"><img src=\"/semi/resources/images/주문관리.jpg\">주문관리</a><br>\r\n");
      out.write("\r\n");
      out.write("<!-- 실시간 랭킹바  -->\r\n");
      out.write("<select id=\"rank\" name=\"rank\">\r\n");
      out.write("\t<option id=\"rank1\">1.</option>\r\n");
      out.write("\t<option id=\"rank2\">2. </option>\r\n");
      out.write("\t<option id=\"rank3\">3.</option>\r\n");
      out.write("\t<option id=\"rank4\">4. </option>\r\n");
      out.write("\t<option id=\"rank5\">5. </option>\r\n");
      out.write("\t<option id=\"rank6\">6. </option>\r\n");
      out.write("\t<option id=\"rank7\">7. </option>\r\n");
      out.write("\t<option id=\"rank8\">8.></option>\r\n");
      out.write("\t<option id=\"rank9\">9. </option>\r\n");
      out.write("\t<option id=\"rank10\">10.</option>\r\n");
      out.write("</select>\r\n");
      out.write("<button id=\"myBtn\" onclick=\"\"><img src=\"/semi/resources/images/검색.jpg\"></button>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!--  메뉴 바 -->\r\n");
      out.write("<ul id=\"navi\">\t\r\n");
      out.write("<li class=\"on\"><a href=\"index.jsp\">MEN</a>\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t\t<li><a href=\"#\">1</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\">2</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\">3</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\">4</a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"index.jsp\">WOMEN</a>\r\n");
      out.write("<ul>\r\n");
      out.write("\t\t<li><a href=\"#\">1</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\">2</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\">3</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\">4</a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"index.jsp\">BRAND</a>\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t\t<li><a href=\"#\">1</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\">2</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\">3</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\">4</a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"index.jsp\">ACC</a>\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t\t<li><a href=\"#\">1</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\">2</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\">3</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\">4</a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"index.jsp\">BRAND</a>\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t\t<li><a href=\"#\">1</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\">2</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\">3</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\">4</a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("</li>\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("<br><br>\r\n");
      out.write("<br><br>\r\n");
      out.write("<br><br>\r\n");
      out.write("<br><br>\r\n");
      out.write("<br><br>\r\n");
      out.write("<br><br>\r\n");
      out.write("<!-- 검색창  -->\r\n");
      out.write("</header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<h2>시발년아</h2>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".address {\r\n");
      out.write(" font-size:small;\r\n");
      out.write(" }\r\n");
      out.write(" #footer{\r\n");
      out.write(" position:static;\r\n");
      out.write(" bottom:0;\r\n");
      out.write(" width:98vw;\r\n");
      out.write(" align:center;\r\n");
      out.write(" \r\n");
      out.write(" }\r\n");
      out.write(" #footer p{\r\n");
      out.write(" color:rgba(0,0,0,0.5);\r\n");
      out.write(" }\r\n");
      out.write(" #footer a {\r\n");
      out.write(" color:black;\r\n");
      out.write(" }\r\n");
      out.write(" #footer div {\r\n");
      out.write(" margin:20px;\r\n");
      out.write(" padding:20px;\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write("</style>\r\n");
      out.write("<body style=\"margin:0px; padding:0px;\">\r\n");
      out.write("<footer id=\"footer\" >\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("<hr>\r\n");
      out.write("<img src=\"/semi/resources/images/로고2.png\" style=\"width:40px;height:40px;float:left;\"><h1>1644-1234</h1>\r\n");
      out.write("<p style=\"font-size:small\">AM 10:00 ~ PM 05:00<BR>\r\n");
      out.write("Off-Time PM 12:00 ~ PM 2:00<BR>\r\n");
      out.write("DAY OFF (SATURDAY,SUNDAY,HOLIDAY)\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("<a href=\"#\">개인정보취급방침 | 이용약관</a>\r\n");
      out.write("<p class=\"address\">주식회사 그랩(GRAB Co.,Ltd) | 서울특별시 강남구 신사동 640-2 로빈명품관 지하1층 | 사업자등록번호 : 211-88-79575 |<br>\r\n");
      out.write("통신판매업 : 2012-서울강남-01897 | 대표 : 조만호 | 개인정보관리책임자 : 심준섭(<a href=\"mailto:help@musinsa.com\">help@musinsa.com</a>) ｜ 호스팅사업자 : ㈜이호스트ICT</p>\r\n");
      out.write("</div>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
